### ISSUE TITLE
chronic end bug with geedy Search

### ISSUE THREAD

**Issue by luvf** [MarvinLer/pypownet#26]
running with 
 python -m pypownet.main --parameters parameters/default14 -lv hard -a TreeSearchLineServiceStatus -n 10000    

this happen with an agent that use predict. at the last timestep of a chronic the predict  &, to counter this problem 
switch to the next chronic one timstep earlier

proposition  int game.py line 345 replace : 
if self.current_timestep_id == timesteps_ids[-1]:
by 
if self.current_timestep_id == timesteps_ids[-3]:
#changing by -2 doesn't work

**Comment by MarvinLer** [comment]
Hi, thanks for the feedback, I will look into it later today.
Your quickfix should be enough for the TreeSearchLineServiceStatus agent, but would not work for agents that use predict for more that one timestep in the future, so I will correct the behavior for the general usage.

**Comment by MarvinLer** [comment]
A chronic loading bug was fixed in 2420691dce9b12557ef9125df8d9f44395025f09 regarding the use of simulation function at the end of chronics. Basically at the last timestep of a chronic, the simulation function used to load the next chronic, and the subsequent 1 timestep rollback loaded the last (-1) timestep of the latter, which created a evergoing loop of chronic loading.
Now, when using the prediction during the last timestep of a chronic (ie there are no more timestep to be played for this chronic), the game will feed the agent by mirroring the last timestep of the chronic; that is, until a real environment.step() is performed in which case the first timestep of the next chronic is loaded, as expected.

Was it the bug you have experienced @luvf ? otherwise could you provide me a screenshot ?

**Comment by luvf** [comment]
no this haven't changed anything, I still have that :
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/to/pypownet/main.py", line 63, in <module>
    main()
  File "/home/to/pypownet/main.py", line 58, in main
    final_reward = runner.loop(iterations=args.niter)
  File "/home/to/pypownet/runner.py", line 111, in loop
    (obs, act, rew) = self.step()
  File "/home/to/pypownet/runner.py", line 80, in step
    action = self.agent.act(self.last_observation)
  File "/home/to/pypownet/agent.py", line 131, in act
    simulated_reward = self.environment.simulate(action=action)
  File "/home/to/pypownet/environment.py", line 611, in simulate
    observation, reward_flag, done = self.game.simulate(to_simulate_action)
  File "/home/to/pypownet/game.py", line 606, in simulate
    simulated_obs, flag, done = self.step(action, _is_simulation=True)
  File "/home/to/pypownet/game.py", line 556, in step
    self._compute_loadflow_cascading()
  File "/home/to/pypownet/game.py", line 370, in _compute_loadflow_cascading
    self.grid.compute_loadflow(fname_end='_cascading%d' % depth)
  File "/home/to/pypownet/grid.py", line 244, in compute_loadflow
    output, loadflow_success = self.__vanilla_loadflow_backend_callback(fname_end=fname_end)
  File "/home/to/pypownet/grid.py", line 218, in __vanilla_loadflow_backend_callback
    output, loadflow_success = function(self.mpc, self.loadflow_options, pprint, fname)
  File "/usr/lib/python3.7/site-packages/PYPOWER-5.1.4-py3.7.egg/pypower/rundcpf.py", line 26, in rundcpf
    return runpf(casedata, ppopt, fname, solvedcase)
  File "/usr/lib/python3.7/site-packages/PYPOWER-5.1.4-py3.7.egg/pypower/runpf.py", line 99, in runpf
    ref, pv, pq = bustypes(bus, gen)
  File "/usr/lib/python3.7/site-packages/PYPOWER-5.1.4-py3.7.egg/pypower/bustypes.py", line 47, in bustypes
    ref[0] = pv[0]      # use the first PV bus
IndexError: index 0 is out of bounds for axis 0 with size 0
zsh: exit 1     python -m pypownet.main --parameters parameters/default14 -lv hard -a  -n 


to reproduce (easly and fast) :
use TreeSearchLineServiceStatus
and modify line 126  
for l in range(number_of_lines):
to 
for l in range(2):

**Comment by MarvinLer** [comment]
Thanks for the error traces. This appear to be a bug raised within pypownet (the loadflow computation library) and apparently, this is provoked because there are no generators available (pv[0] raises out of index). This should be have been managed by the game, so not sure where this come from, will investigate shortly.

**Comment by MarvinLer** [comment]
Fixed in 2392d9a7224a111092dfabf8e589845a10d67f8d. So the bug happened when all production were off (eg maintenance) but still under the max tolerated disconnected productions. Since this represents a global outage, the game will now raise a pypownet.game.DivergingLoadflowException which corresponds to global outage cases.
Can you confirm it is OK for you now ?

**Comment by MarvinLer** [comment]
Hi @luvf , please reopen the issue if you still stumble upon this bug.
